# fly.toml app configuration file generated for simple-chain-winter-glade-6079-silent-haze-1524 on 2024-01-19T14:47:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simple-chain-winter-glade-6079-silent-haze-1524"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
